import { Component, OnInit } from '@angular/core';
import {FormsModule} from '@angular/forms';
import {Router} from '@angular/router';

var count = 1;

@Component({
  selector: 'app-login',
  templateUrl: './login.component.html',
  styleUrls: ['./login.component.css']
})
export class LoginComponent implements OnInit {
  username:string ='';
  password:string ='';
  constructor(private router:Router, private form:FormsModule) { console.log("Consgructor")}

  ngOnInit() {
  }

  // Check if server has these login details.
  fetchingData(url, finish, cannot) {
    fetch(url)
      .then(response => {return response.json()})
      .then(myJson => {
        console.log(myJson);
        if (myJson.success === true) {
          finish(myJson);
        } else {
          cannot();
        }
    })
  }

  /* Alert to inform user that the username or password is incorrect.
  */
  falseLogin() {
    alert("Username or Password were incorrect");
  }

  /* Sets the local storage variables with username and user type, specified by ID.
   * Parameter: data: The correct username and ID type returned from the server.
  */
  finishLogin(data) {

      if (typeof(Storage) !== "undefined") {
        sessionStorage.setItem("username", data.username);
        sessionStorage.setItem("id", data.type);
        console.log(sessionStorage.getItem("id"));
        console.log(sessionStorage.getItem("username"));
        this.router.navigateByUrl('/controlpanel');
      } else {
        alert("Do not sessions, cannot log in");
      }
}


  /* Attempts to log the user in.
   * Parameter: event: The event generated by Angular is not used.
  */
  loginUser(event) {
    event.preventDefault();

    // Access to all our variables within this class because it's asyncronous.
    let falseBind = this.falseLogin.bind(this);
    let finishBind = this.finishLogin.bind(this);
    // route url to server
    let url = '/server/login?username=' + this.username +'&password=' +this.password;
    this.fetchingData(url, finishBind, falseBind);


  }
}
